name: Daily Hulk Bot
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install FFmpeg & Libs
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install gTTS requests
      - name: Run Bot
        run: python bot.py
      - name: Save Video to Repo
        run: |
          git config --global user.name "HulkBot"
          git config --global user.email "bot@hulk.com"
          git add short_video.mp4
          git commit -m "New Daily Short Created"
          git push
